# Generated by Django 3.1.6 on 2021-02-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ctors',
            new_name='actors',
        ),
    ]
